### ISSUE TITLE
Integrate this repo with the integration issue tracker

### ISSUE THREAD

**Issue by bgyori** [AlgebraicJulia/py-acsets#16]
Would be nice to be able to add labels so that issues here pop up on https://github.com/orgs/DARPA-ASKEM/projects/5

**Comment by olynch** [comment]
How does that work?

**Comment by bgyori** [comment]
Here are the instructions: https://docs.google.com/document/d/1_RvLMZ3KZChyR02yn-EdeOJWi9QmdrzUPZYgxKp48Y4/edit?usp=sharing

**Comment by p-stokes** [comment]
This has now been added.
