### ISSUE TITLE
Add a test with properties on species and transitions

### ISSUE THREAD

**Issue by bgyori** [AlgebraicJulia/py-acsets#4]
It would be helpful to see how one can add further properties to species and transitions. The current test case adds `s`, `i` and `r` without any properties, perhaps a variant where these are given names would be helpful for me to see how to do that!

**Comment by jpfairbanks** [comment]
I think that Justin has a branch that has attributes because he is using sname and tname feeding into the ODESystem generation.

**Comment by bgyori** [comment]
This is now all done
